### ISSUE TITLE
1.9.0 release jar issue

### ISSUE THREAD

**Issue by chenrui333** [google/google-java-format#1014]
There is some issue with the `google-java-format-1.19.0-all-deps.jar` jar.

```
$ java --version
openjdk 21 2023-09-19 LTS
OpenJDK Runtime Environment Corretto-21.0.0.35.1 (build 21+35-LTS)
OpenJDK 64-Bit Server VM Corretto-21.0.0.35.1 (build 21+35-LTS, mixed mode, sharing)

$ cat foo.java
public class Foo{
}

$ java -jar /Users/rui/Downloads/google-java-format-1.19.0-all-deps.jar  foo.java
error: com.google.googlejavaformat.java.java21.Java21InputAstVisitor
java.lang.LinkageError: com.google.googlejavaformat.java.java21.Java21InputAstVisitor
	at com.google.googlejavaformat.java.Formatter.createVisitor(Formatter.java:182)
	at com.google.googlejavaformat.java.Formatter.format(Formatter.java:156)
	at com.google.googlejavaformat.java.Formatter.getFormatReplacements(Formatter.java:283)
	at com.google.googlejavaformat.java.Formatter.formatSource(Formatter.java:257)
	at com.google.googlejavaformat.java.FormatFileCallable.call(FormatFileCallable.java:75)
	at com.google.googlejavaformat.java.FormatFileCallable.call(FormatFileCallable.java:29)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.ClassNotFoundException: com.google.googlejavaformat.java.java21.Java21InputAstVisitor
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:421)
	at java.base/java.lang.Class.forName(Class.java:412)
	at com.google.googlejavaformat.java.Formatter.createVisitor(Formatter.java:177)
	... 11 more
```

**Comment by chenrui333** [comment]
> If somebody needs a temporary workaround for this, recompiling locally with jdk 21 works for me.

that is a good pointer, I will try out jdk17 for now then. Thanks!

**Comment by cushon** [comment]
Thanks @EvaristeGalois11 for the PR, I will get a new point release out today after that's merged.

**Comment by cushon** [comment]
I pushed a 1.19.1 release that fixes the crash on JDK 21: https://github.com/google/google-java-format/releases/tag/v1.19.1

```
$ java --version
openjdk 21.0.1 2023-10-17 LTS

$ java -jar google-java-format-1.19.0-all-deps.jar foo.java
error: com.google.googlejavaformat.java.java21.Java21InputAstVisitor
java.lang.LinkageError: com.google.googlejavaformat.java.java21.Java21InputAstVisitor
	at com.google.googlejavaformat.java.Formatter.createVisitor(Formatter.java:182)
	at com.google.googlejavaformat.java.Formatter.format(Formatter.java:156)
	at com.google.googlejavaformat.java.Formatter.getFormatReplacements(Formatter.java:283)
	at com.google.googlejavaformat.java.Formatter.formatSource(Formatter.java:257)
	at com.google.googlejavaformat.java.FormatFileCallable.call(FormatFileCallable.java:75)
	at com.google.googlejavaformat.java.FormatFileCallable.call(FormatFileCallable.java:29)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.ClassNotFoundException: com.google.googlejavaformat.java.java21.Java21InputAstVisitor
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:421)
	at java.base/java.lang.Class.forName(Class.java:412)
	at com.google.googlejavaformat.java.Formatter.createVisitor(Formatter.java:177)
	... 11 more
	
$  java -jar google-java-format-1.19.1-all-deps.jar foo.java
public class Foo {}
```

**Comment by chenrui333** [comment]
@cushon thanks for the quick turnaround! 🙏
