### ISSUE TITLE
help

### ISSUE THREAD

**Issue by appt2** [google/google-java-format#1042]
```
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/sun/tools/javac/parser/Tokens$TokenKind;
02-09 18:38:58.685 30238 30238 E  AndroidRuntime:           	at com.google.googlejavaformat.java.ImportOrderer.<clinit>(ImportOrderer.java:111)
02-09 18:38:58.685 30238 30238 E  AndroidRuntime:           	at com.google.googlejavaformat.java.Formatter.formatSourceAndFixImports(Formatter.java:239)
02-09 18:38:58.685 30238 30238 E  AndroidRuntime:           	at ninja.coder.thememanagerlibrary.GoogleJavaFormatter.format(GoogleJavaFormatter.java:23)
02-09 18:38:58.685 30238 30238 E  AndroidRuntime:           	at ninja.coder.thememanagerlibrary.MainActivity.lambda$onCreate$0$ninja-coder-thememanagerlibrary-MainActivity(MainActivity.java:45)
02-09 18:38:58.685 30238 30238 E  AndroidRuntime:           	at ninja.coder.thememanagerlibrary.MainActivity$$ExternalSyntheticLambda0.onClick(Unknown Source:2)
02-09 18:38:58.685 30238 30238 E  AndroidRuntime:           	at android.view.View.performClick(View.java:7798)
02-09 18:38:58.685 30238 30238 E  AndroidRuntime:           	at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1211)
02-09 18:38:58.685 30238 30238 E  AndroidRuntime:           	at android.view.View.performClickInternal(View.java:7775)
02-09 18:38:58.685 30238 30238 E  AndroidRuntime:           	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
02-09 18:38:58.685 30238 30238 E  AndroidRuntime:           	at android.view.View$PerformClick.run(View.java:31222)
02-09 18:38:58.685 30238 30238 E  AndroidRuntime:           	at android.os.Handler.handleCallback(Handler.java:958)
02-09 18:38:58.685 30238 30238 E  AndroidRuntime:           	at android.os.Handler.dispatchMessage(Handler.java:99)
02-09 18:38:58.685 30238 30238 E  AndroidRuntime:           	at android.os.Looper.loopOnce(Looper.java:224)
02-09 18:38:58.685 30238 30238 E  AndroidRuntime:           	at android.os.Looper.loop(Looper.java:318)
02-09 18:38:58.685 30238 30238 E  AndroidRuntime:           	at android.app.ActivityThread.main(ActivityThread.java:8762)
02-09 18:38:58.685 30238 30238 E  AndroidRuntime:           	at java.lang.reflect.Method.invoke(Native Method)
02-09 18:38:58.685 30238 30238 E  AndroidRuntime:           	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
02-09 18:38:58.685 30238 30238 E  AndroidRuntime:           	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
02-09 18:38:58.685 30238 30238 E  AndroidRuntime:           Caused by: java.lang.ClassNotFoundException: Didn't find class "com.sun.tools.javac.parser.Tokens$TokenKind" on path: DexPathList[[zip file "/data/app/Hxsyqvbfvv9WTxDtjrO9OA==/ninja.coder.thememanagerlibrary-rDvt7GauJypb35lmW5aBqw==/base.apk"],nativeLibraryDirectories=[/data/app/Hxsyqvbfvv9WTxDtjrO9OA==/ninja.coder.thememanagerlibrary-rDvt7GauJypb35lmW5aBqw==/lib/arm64, /system/lib64, /system_ext/lib64]]
02-09 18:38:58.685 30238 30238 E  AndroidRuntime:           	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
02-09 18:38:58.685 30238 30238 E  AndroidRuntime:           	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
02-09 18:38:58.685 30238 30238 E  AndroidRuntime:           	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
02-09 18:38:58.685 30238 30238 E  AndroidRuntime:           	... 18 more
```

hi I added the dependency but I still get this error in the android project

**Comment by vorburger** [comment]
@appt2 I don't think you can use this as a library on Android. 

As far as I know the Android runtime doesn't include `javac`, which this needs.

OK for you to close this issue?

**Comment by vorburger** [comment]
> so have to adding in gradel?

No, I don't think you can use this as a library on Android; it won't work.

**Comment by cushon** [comment]
> No, I don't think you can use this as a library on Android; it won't work.

That's accurate, it depends on APIs that aren't available on Android.
