### ISSUE TITLE
Missing resource bundle for GJF 1.2 + Maven

### ISSUE THREAD

**Issue by ronshapiro** [google/google-java-format#114]
When upgrading Dagger to use GJF 1.2, our bazel build passes but maven tests fail with the following error:

```
Fatal error compiling: java.lang.InternalError: Cannot find requested resource bundle for locale en_US: Can't find bundle for base name org.openjdk.tools.javac.resources.compiler, locale en_US
```

Some thoughts:
 - That seems to be pointing to this [file](http://hg.openjdk.java.net/jdk9/client/langtools/file/b95622ea8356/src/jdk.compiler/share/classes/com/sun/tools/javac/resources/compiler.properties)
- Maybe Bazel has this already on the classpath which is why it is succeeding there?
- That file (nor does any other resource) appear in [javac-9-dev-r3297-1-shaded.jar](https://oss.sonatype.org/content/repositories/public/com/google/errorprone/javac/9-dev-r3297-1-shaded/javac-9-dev-r3297-1-shaded.jar) AFAICT

**Comment by cushon** [comment]
The resources are present as classfiles:

```
$ jar tf ./javac-9-dev-r3297-1-shaded.jar  | grep 'resources/compiler'
...
org/openjdk/tools/javac/resources/compiler_zh_CN.class
org/openjdk/tools/javac/resources/compiler_ja.class
org/openjdk/tools/javac/resources/compiler.class
```

But they're being lost in the shaded dagger jar:

```
$ jar tf ./dagger-compiler-HEAD-SNAPSHOT.jar | grep 'resources/compiler'
...
```

If all of `com.google.errorprone:javac` is included in the shaded jar the maven tests pass.

And here's the stack trace, for posterity:

<details><p>

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project guava-functional-tests: Fatal error compiling: java.lang.InternalError: Cannot find requested resource bundle for locale en_US: Can't find bundle for base name org.openjdk.tools.javac.resources.compiler, locale en_US -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project guava-functional-tests: Fatal error compiling
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Fatal error compiling
	at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:796)
	at org.apache.maven.plugin.compiler.CompilerMojo.execute(CompilerMojo.java:129)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more
Caused by: org.codehaus.plexus.compiler.CompilerException: java.lang.InternalError: Cannot find requested resource bundle for locale en_US
	at org.codehaus.plexus.compiler.javac.JavaxToolsCompiler.compileInProcess(JavaxToolsCompiler.java:191)
	at org.codehaus.plexus.compiler.javac.JavacCompiler.performCompile(JavacCompiler.java:169)
	at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:785)
	... 23 more
Caused by: java.lang.RuntimeException: java.lang.InternalError: Cannot find requested resource bundle for locale en_US
	at com.sun.tools.javac.main.Main.compile(Main.java:553)
	at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
	at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
	at org.codehaus.plexus.compiler.javac.JavaxToolsCompiler.compileInProcess(JavaxToolsCompiler.java:126)
	... 25 more
Caused by: java.lang.InternalError: Cannot find requested resource bundle for locale en_US
	at org.openjdk.tools.javac.util.JavacMessages.getBundles(JavacMessages.java:128)
	at org.openjdk.tools.javac.util.JavacMessages.setCurrentLocale(JavacMessages.java:72)
	at org.openjdk.tools.javac.util.JavacMessages.<init>(JavacMessages.java:97)
	at org.openjdk.tools.javac.util.JavacMessages.<init>(JavacMessages.java:79)
	at org.openjdk.tools.javac.util.JavacMessages.instance(JavacMessages.java:53)
	at org.openjdk.tools.javac.util.JCDiagnostic$Factory.<init>(JCDiagnostic.java:71)
	at org.openjdk.tools.javac.util.JCDiagnostic$Factory.instance(JCDiagnostic.java:61)
	at org.openjdk.tools.javac.util.Log.<init>(Log.java:229)
	at org.openjdk.tools.javac.util.Log.<init>(Log.java:314)
	at org.openjdk.tools.javac.util.Log.<init>(Log.java:308)
	at org.openjdk.tools.javac.util.Log.instance(Log.java:321)
	at org.openjdk.tools.javac.file.BaseFileManager.setContext(BaseFileManager.java:85)
	at org.openjdk.tools.javac.file.JavacFileManager.setContext(JavacFileManager.java:149)
	at org.openjdk.tools.javac.file.JavacFileManager.<init>(JavacFileManager.java:141)
	at com.google.googlejavaformat.java.JavaInput.buildToks(JavaInput.java:349)
	at com.google.googlejavaformat.java.JavaInput.buildToks(JavaInput.java:332)
	at com.google.googlejavaformat.java.JavaInput.<init>(JavaInput.java:274)
	at com.google.googlejavaformat.java.Formatter.getFormatReplacements(Formatter.java:229)
	at com.google.googlejavaformat.java.Formatter.formatSource(Formatter.java:216)
	at com.google.googlejavaformat.java.Formatter.formatSource(Formatter.java:202)
	at com.google.googlejavaformat.java.Formatter.formatSource(Formatter.java:191)
	at com.google.googlejavaformat.java.filer.FormattingJavaFileObject$1.close(FormattingJavaFileObject.java:56)
	at com.squareup.javapoet.JavaFile.writeTo(JavaFile.java:117)
	at dagger.internal.codegen.SourceFileGenerator.generate(SourceFileGenerator.java:77)
	at dagger.internal.codegen.SourceFileGenerator.generate(SourceFileGenerator.java:63)
	at dagger.internal.codegen.ModuleProcessingStep$ProvisionModuleMethodFactoryGenerator.generate(ModuleProcessingStep.java:164)
	at dagger.internal.codegen.ModuleProcessingStep.processModule(ModuleProcessingStep.java:130)
	at dagger.internal.codegen.ModuleProcessingStep.process(ModuleProcessingStep.java:117)
	at dagger.shaded.auto.common.BasicAnnotationProcessor.process(BasicAnnotationProcessor.java:329)
	at dagger.shaded.auto.common.BasicAnnotationProcessor.process(BasicAnnotationProcessor.java:182)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:705)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)
	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
	at com.sun.tools.javac.main.Main.compile(Main.java:523)
	... 28 more
Caused by: java.util.MissingResourceException: Can't find bundle for base name org.openjdk.tools.javac.resources.compiler, locale en_US
	at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1564)
	at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1387)
	at java.util.ResourceBundle.getBundle(ResourceBundle.java:845)
	at org.openjdk.tools.javac.util.JavacMessages.lambda$add$0(JavacMessages.java:106)
	at org.openjdk.tools.javac.util.JavacMessages$$Lambda$55/244190700.getResourceBundle(Unknown Source)
	at org.openjdk.tools.javac.util.JavacMessages.getBundles(JavacMessages.java:125)
	... 65 more
```
</p></details>
