### ISSUE TITLE
Exception thrown when ImportOrderer.reorderImports sees imports separated by comment (google-java-format 1.2)

### ISSUE THREAD

**Issue by jbduncan** [google/google-java-format#116]
Steps to reproduce
====
1. `git clone https://github.com/apache/geode.git`
2. `cd geode`
3. `git checkout develop`
3. Open `build.gradle` in a text editor and replace line 27 with...
```gradle
    classpath "com.diffplug.spotless:spotless-plugin-gradle:3.0.0"
```
and line 100 with:
```gradle
      googleJavaFormat('1.2')
```
4. Back at the terminal, execute `gradlew.bat spotlessCheck` (Windows) or `./gradlew spotlessCheck` (Unix).

Part of stack trace
====
```text
Unable to apply step 'google-java-format' to 'src\test\java\org\apache\geode\internal\jta\JTAUtils.java
java.lang.reflect.InvocationTargetException
        at sun.reflect.GeneratedMethodAccessor357.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.diffplug.spotless.java.GoogleJavaFormatStep$State.lambda$createFormat$17(GoogleJavaFormatStep.java:96)
        at com.diffplug.spotless.FormatterStepImpl$Standard.format(FormatterStepImpl.java:75)
        at com.diffplug.spotless.FormatterStep$Strict.format(FormatterStep.java:75)
        at com.diffplug.spotless.Formatter.compute(Formatter.java:177)
        at com.diffplug.spotless.Formatter.applyToAndReturnResultIfDirty(Formatter.java:145)
        at com.diffplug.gradle.spotless.SpotlessTask.apply(SpotlessTask.java:166)
        at com.diffplug.gradle.spotless.SpotlessTask.performAction(SpotlessTask.java:149)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        ...
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: com.google.googlejavaformat.java.FormatterException: error: Imports not contiguous (perhaps a comment separates them?)
        at com.google.googlejavaformat.java.ImportOrderer.reorderImports(ImportOrderer.java:114)
        at com.google.googlejavaformat.java.ImportOrderer.reorderImports(ImportOrderer.java:36)
        ... 92 more
```

**Comment by sormuras** [comment]
It's working (read throwing) as intended (read tested): https://github.com/google/google-java-format/blob/master/core/src/test/java/com/google/googlejavaformat/java/ImportOrdererTest.java#L261 ff

**Comment by jbduncan** [comment]
Thanks for pointing that test out for me @sormuras.

I think I can see now why comments aren't supported. It's because it wouldn't be clear where google-java-format should put the comments after the imports have been re-ordered, isn't it?

When I try using the Eclipse formatter instead to reorder imports, I notice that when there _are_ comments in between the imports of a Java file, those comments are simply _removed_, which I wouldn't want google-java-format to emulate!

Therefore I'm happy to close this issue, as I agree that it's working as intended.

**Comment by aaime** [comment]
The formatter is however failing for files that have a single import, for example:

````
/*
 *    GeoTools - The Open Source Java GIS Toolkit
 *    http://geotools.org
 *
 *    (C) 2011, Open Source Geospatial Foundation (OSGeo)
 *    (C) 2005 Open Geospatial Consortium Inc.
 *    (C) 2001-2004 EXSE, Department of Geography, University of Bonn
 *                  lat/lon Fitzke/Fretter/Poth GbR
 *
 *    This library is free software; you can redistribute it and/or
 *    modify it under the terms of the GNU Lesser General Public
 *    License as published by the Free Software Foundation; either
 *    version 2.1 of the License, or (at your option) any later version.
 *
 *    This library is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *    Lesser General Public License for more details.
 */
package org.opengis.filter.capability;

import java.util.Collection;

// OpenGIS direct dependencies

/**
 * Indicates support for the named spatial operator.
 *
 * <p>The filter that is supported is indicated by the getName() field, these names matc
 *
 * <ul>
 *   <li>A subclass of Filter. Examples include "BBOX" and "Beyond"
 * </ul>
 *
 * Each filter subclass has an associated name, you can use this name to determine if a matching
 * SpatialOperator is defined as part of FilterCapabilities.
 *
 * @author <a href="mailto:schneider@lat-lon.de">Markus Schneider </a>
 * @source $URL$
 */
public interface SpatialOperator extends Operator {
    /** Returns the geometryOperands. */
    Collection<GeometryOperand> getGeometryOperands();
}
````
Now, it's true that the comment there is not very useful, but it's not like it's in the middle of imports :-)

**Comment by aaime** [comment]
Never mind, ignore the comment, I had a same named class in a different package :)

**Comment by jbduncan** [comment]
Hi @aaime! I'm glad to hear that this issue is not such a problem for you anymore.

(I was going to ask for clarification to see if it was worth opening a new issue for your case).

But I admit that I don't understand _why_ it's not a problem for you anymore.

Would you mind clarifying for me? :)

**Comment by aaime** [comment]
I had two classes with the same name in two different packages of the same project. The formatted reported one as being the problem, and I opened by class name in the IDE, ending up in the other, thinking "hey, this one has no problem?". And indeed it did not :-)
Sorry for the noise!

**Comment by jbduncan** [comment]
No worries! Thanks for explaining things further for me. :D
