### ISSUE TITLE
Java 9 - new try-with-resources syntax not supported

### ISSUE THREAD

**Issue by sormuras** [google/google-java-format#155]
```
void walkAndClose(Stream<?> stream) {
  try (stream) {...}
}
```

> Allow effectively-final variables to be used as resources in the try-with-resources statement.
https://docs.oracle.com/javase/9/whatsnew/toc.htm#JSNEW-GUID-825576B5-203C-4C8D-85E5-FFDA4CA0B346

<details>
<summary>java.lang.ClassCastException</summary>

```
>>>> 3719: java.lang.ClassCastException: org.openjdk.tools.javac.tree.JCTree$JCIdent cannot be cast to org.openjdk.source.tree.VariableTree
	at com.google.googlejavaformat.java.JavaInputAstVisitor.visitTry(JavaInputAstVisitor.java:1753)
	at com.google.googlejavaformat.java.JavaInputAstVisitor.visitTry(JavaInputAstVisitor.java:142)
	at org.openjdk.tools.javac.tree.JCTree$JCTry.accept(JCTree.java:1292)
	at org.openjdk.source.util.TreePathScanner.scan(TreePathScanner.java:71)
	at com.google.googlejavaformat.java.JavaInputAstVisitor.scan(JavaInputAstVisitor.java:314)
	at com.google.googlejavaformat.java.JavaInputAstVisitor.visitStatements(JavaInputAstVisitor.java:2034)
	at com.google.googlejavaformat.java.JavaInputAstVisitor.methodBody(JavaInputAstVisitor.java:1444)
	at com.google.googlejavaformat.java.JavaInputAstVisitor.visitMethod(JavaInputAstVisitor.java:1431)
	at com.google.googlejavaformat.java.JavaInputAstVisitor.visitMethod(JavaInputAstVisitor.java:142)
	at org.openjdk.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:868)
	at org.openjdk.source.util.TreePathScanner.scan(TreePathScanner.java:71)
	at com.google.googlejavaformat.java.JavaInputAstVisitor.scan(JavaInputAstVisitor.java:314)
	at com.google.googlejavaformat.java.JavaInputAstVisitor.addBodyDeclarations(JavaInputAstVisitor.java:3242)
	at com.google.googlejavaformat.java.JavaInputAstVisitor.visitClassDeclaration(JavaInputAstVisitor.java:1856)
	at com.google.googlejavaformat.java.JavaInputAstVisitor.visitClass(JavaInputAstVisitor.java:386)
	at com.google.googlejavaformat.java.JavaInputAstVisitor.visitClass(JavaInputAstVisitor.java:142)
	at org.openjdk.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:778)
	at org.openjdk.source.util.TreePathScanner.scan(TreePathScanner.java:71)
	at com.google.googlejavaformat.java.JavaInputAstVisitor.scan(JavaInputAstVisitor.java:314)
	at com.google.googlejavaformat.java.JavaInputAstVisitor.addBodyDeclarations(JavaInputAstVisitor.java:3242)
	at com.google.googlejavaformat.java.JavaInputAstVisitor.visitClassDeclaration(JavaInputAstVisitor.java:1856)
	at com.google.googlejavaformat.java.JavaInputAstVisitor.visitClass(JavaInputAstVisitor.java:386)
	at com.google.googlejavaformat.java.JavaInputAstVisitor.visitClass(JavaInputAstVisitor.java:142)
	at org.openjdk.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:778)
	at org.openjdk.source.util.TreePathScanner.scan(TreePathScanner.java:71)
	at com.google.googlejavaformat.java.JavaInputAstVisitor.scan(JavaInputAstVisitor.java:314)
	at com.google.googlejavaformat.java.JavaInputAstVisitor.visitCompilationUnit(JavaInputAstVisitor.java:358)
	at com.google.googlejavaformat.java.JavaInputAstVisitor.visitCompilationUnit(JavaInputAstVisitor.java:142)
	at org.openjdk.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:561)
	at org.openjdk.source.util.TreePathScanner.scan(TreePathScanner.java:71)
	at com.google.googlejavaformat.java.JavaInputAstVisitor.scan(JavaInputAstVisitor.java:314)
	at com.google.googlejavaformat.java.Formatter.format(Formatter.java:172)
	at com.google.googlejavaformat.java.Formatter.getFormatReplacements(Formatter.java:240)
	at com.google.googlejavaformat.java.Formatter.formatSource(Formatter.java:216)
	at com.google.googlejavaformat.java.FormatFileCallable.call(FormatFileCallable.java:46)
	at com.google.googlejavaformat.java.FormatFileCallable.call(FormatFileCallable.java:27)
```
</details>

## Work-around
If you replace the `try(stream)` with `try {...} finally { stream.close(); }` everything works fine.

**Comment by sormuras** [comment]
After the update of `javac` in 

the ClassCastException is no longer thrown, but the new syntax is still not supported "out-of-box". Maybe, the `-source 9` option could help here, too? Like in #176.
```
error: illegal start of expression
```

**Comment by sormuras** [comment]
`-source 9` would help:

```
variables in try-with-resources not supported in -source 1.8
  (use -source 9 or higher to enable variables in try-with-resources)
```

**Comment by sormuras** [comment]
The ClassCastException returns with `-source 9` being set:
```
>>>> 119: java.lang.ClassCastException: org.openjdk.tools.javac.tree.JCTree$JCIdent cannot be cast to org.openjdk.source.tree.VariableTree
	at com.google.googlejavaformat.java.JavaInputAstVisitor.visitTry(JavaInputAstVisitor.java:1760)
	at com.google.googlejavaformat.java.JavaInputAstVisitor.visitTry(JavaInputAstVisitor.java:142)
	at org.openjdk.tools.javac.tree.JCTree$JCTry.accept(JCTree.java:1322)
	at org.openjdk.source.util.TreePathScanner.scan(TreePathScanner.java:82)
```
