### ISSUE TITLE
Java 9 - RemoveUnusedImports needs "-source 9" too

### ISSUE THREAD

**Issue by sormuras** [google/google-java-format#181]
Analogue to #176 the "import fixer" needs the `-source 9` as well.

Stacktrace:

```
com.google.googlejavaformat.FormattingError: 470:35:
  error: private interface methods are not supported in -source 1.8
  (use -source 9 or higher to enable private interface methods)

	at com.google.googlejavaformat.FormattingError.fromJavacDiagnostics(FormattingError.java:46)
	at com.google.googlejavaformat.java.RemoveUnusedImports.parse(RemoveUnusedImports.java:241)
	at com.google.googlejavaformat.java.RemoveUnusedImports.removeUnusedImports(RemoveUnusedImports.java:198)
	at com.google.googlejavaformat.java.FormatFileCallable.fixImports(FormatFileCallable.java:54)
	at com.google.googlejavaformat.java.FormatFileCallable.call(FormatFileCallable.java:47)
	at com.google.googlejavaformat.java.FormatFileCallable.call(FormatFileCallable.java:27)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.base/java.lang.Thread.run(Thread.java:844)
```

**Comment by sormuras** [comment]
![context](https://user-images.githubusercontent.com/2319838/29547613-7137cc56-86fb-11e7-84be-6b87205bf4ac.PNG)

What about `JavaInput`? It too creates an instance of `Context`...

Thinking about a private helper class that solves _"this should default to the latest supported source level, remove this after backing out"_ and that is referred to by all 3 occurances.

**Comment by cushon** [comment]
> What about JavaInput?

I don't think that one matters currently because it's only doing tokenization, and nothing changed between 8 and 9 there.
