### ISSUE TITLE
crash in JavadocLexer.consumeToken

### ISSUE THREAD

**Issue by msridhar** [google/google-java-format#201]
Input:
```java
public class Foo {
    /** 
     * Set and enable something.
     */
    public void setSomething() {}
}
```

If I try to run GJF on Foo.java, I get the following crash:
```
Foo.java: error: null
java.lang.AssertionError
	at com.google.googlejavaformat.java.javadoc.JavadocLexer.consumeToken(JavadocLexer.java:238)
	at com.google.googlejavaformat.java.javadoc.JavadocLexer.readToken(JavadocLexer.java:131)
	at com.google.googlejavaformat.java.javadoc.JavadocLexer.generateTokens(JavadocLexer.java:113)
	at com.google.googlejavaformat.java.javadoc.JavadocLexer.lex(JavadocLexer.java:74)
	at com.google.googlejavaformat.java.javadoc.JavadocFormatter.formatJavadoc(JavadocFormatter.java:46)
	at com.google.googlejavaformat.java.JavaCommentsHelper.rewrite(JavaCommentsHelper.java:47)
	at com.google.googlejavaformat.Doc$Tok.computeBreaks(Doc.java:755)
	at com.google.googlejavaformat.Doc$Level.computeSplit(Doc.java:330)
	at com.google.googlejavaformat.Doc$Level.computeBreakAndSplit(Doc.java:320)
	at com.google.googlejavaformat.Doc$Level.computeBroken(Doc.java:296)
	at com.google.googlejavaformat.Doc$Level.computeBreaks(Doc.java:266)
	at com.google.googlejavaformat.Doc$Level.computeSplit(Doc.java:330)
	at com.google.googlejavaformat.Doc$Level.computeBreakAndSplit(Doc.java:320)
	at com.google.googlejavaformat.Doc$Level.computeBroken(Doc.java:290)
	at com.google.googlejavaformat.Doc$Level.computeBreaks(Doc.java:266)
	at com.google.googlejavaformat.Doc$Level.computeSplit(Doc.java:330)
	at com.google.googlejavaformat.Doc$Level.computeBreakAndSplit(Doc.java:320)
	at com.google.googlejavaformat.Doc$Level.computeBroken(Doc.java:290)
	at com.google.googlejavaformat.Doc$Level.computeBreaks(Doc.java:266)
	at com.google.googlejavaformat.java.Formatter.format(Formatter.java:181)
	at com.google.googlejavaformat.java.Formatter.getFormatReplacements(Formatter.java:245)
	at com.google.googlejavaformat.java.Formatter.formatSource(Formatter.java:221)
	at com.google.googlejavaformat.java.FormatFileCallable.call(FormatFileCallable.java:46)
	at com.google.googlejavaformat.java.FormatFileCallable.call(FormatFileCallable.java:27)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by cushon** [comment]
@cpovirk FYI
There's a [`  \u2028`](http://www.fileformat.info/info/unicode/char/2028/index.htm) in there (which is [disallowed by the style guide](https://google.github.io/styleguide/javaguide.html#s2.3.1-whitespace-characters)) but it'd be nice not to crash on it.

**Comment by cpovirk** [comment]
Thanks for the report. I've been wishing I'd get around to fuzzing the Javadoc formatter someday. This might be as easy to fix as turning on `DOTALL`. I'll try to give that a shot within the next week.
