### ISSUE TITLE
Can't run google-java-format-1.7.jar

### ISSUE THREAD

**Issue by pablof300** [google/google-java-format#398]
Using openjdk-12.0.1.jdk and running this command:

`java -jar google-java-format-1.7.jar /Users/pablo/IdeaProjects/playground/src/main/java/Playground.java`

but I get following stack trace:

`java.lang.NoClassDefFoundError: com/google/common/base/Splitter
	at com.google.googlejavaformat.java.CommandLineOptionsParser.<clinit>(CommandLineOptionsParser.java:35)
	at com.google.googlejavaformat.java.Main.processArgs(Main.java:217)
	at com.google.googlejavaformat.java.Main.format(Main.java:89)
	at com.google.googlejavaformat.java.Main.main(Main.java:70)
Caused by: java.lang.ClassNotFoundException: com.google.common.base.Splitter
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 4 more
Exception in thread "main" java.lang.NoClassDefFoundError: com/google/common/base/Joiner
	at com.google.googlejavaformat.java.UsageException.<clinit>(UsageException.java:24)
	at com.google.googlejavaformat.java.Main.processArgs(Main.java:222)
	at com.google.googlejavaformat.java.Main.format(Main.java:89)
	at com.google.googlejavaformat.java.Main.main(Main.java:70)
Caused by: java.lang.ClassNotFoundException: com.google.common.base.Joiner
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 4 more`

**Comment by plumpy** [comment]
You need to use google-java-format-1.7-all-deps.jar if you want to run it that way.
