### ISSUE TITLE
Support JEP 361 Switch Expressions (Standard)

### ISSUE THREAD

**Issue by bwRavencl** [google/google-java-format#442]
Formatting a Java 14 source file including a switch expression as described in [JEP 361](https://openjdk.java.net/jeps/361) fails as follows:

```
Caused by: com.google.googlejavaformat.java.FormatterException: 132:131: error: : expected
        at com.google.googlejavaformat.java.FormatterException.fromJavacDiagnostics(FormatterException.java:50)
        at com.google.googlejavaformat.java.Formatter.format(Formatter.java:151)
        at com.google.googlejavaformat.java.Formatter.getFormatReplacements(Formatter.java:258)
        at com.google.googlejavaformat.java.Formatter.formatSource(Formatter.java:234)
        at com.google.googlejavaformat.java.Formatter.formatSource(Formatter.java:202)
        ... 113 more
```

This is issue was already mentioned as part of _Support new Java language features_ #436, however since there seems to exist no dedicated issue for the switch expressions yet I decided to open this one.

Since JDK 14 is scheduled for a production release on March 17, 2020 it would be great to see this fixed soon.

**Comment by sormuras** [comment]
Duplicates #340
