### ISSUE TITLE
minimum supported version in 1.8 broke brew install

### ISSUE THREAD

**Issue by softprops** [google/google-java-format#508]
It seems the latest version [dropped support for java 8](https://github.com/google/google-java-format/releases/tag/google-java-format-1.8) which broke my brew install. 

```
r has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/google/googlejavaformat/java/Main has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:495)
```

I don't actually see a version field in the [brew recipe](https://github.com/Homebrew/homebrew-core/blob/master/Formula/google-java-format.rb)

Is there a workable/recommended solution to stick the the previous version until the env I'm working within until I can update all java environments to java 11?

**Comment by NileshPS** [comment]
This may not be the best work around but you could use [jenv](https://www.jenv.be/) to switch to a supported runtime version before running the jar.

**Comment by softprops** [comment]
That was the path we ended out taking. A better solution would be an ability to use a version provided by the Google java format homebrew recipie instead. There's nothing technically stopping the same problem from happening again with the jenv approach.

**Comment by deanorderly** [comment]
Same here! but from gradle plugin version 0.9.  Anyone know what version works on java 8?

**Comment by deanorderly** [comment]
I don't think mobile devs can really do java 11 yet by the way :(
