### ISSUE TITLE
google-java-format crashes with NoSuchMethodException

### ISSUE THREAD

**Issue by katre** [google/google-java-format#564]
The file in question compiles correctly, but apparently has something wrong that is crashing google-java-format.

Output:
```
$ google-java-format ConfigCommand.java
ConfigCommand.java: error: com.sun.tools.javac.parser.UnicodeReader.getRawCharacters(int, int)
java.lang.LinkageError: com.sun.tools.javac.parser.UnicodeReader.getRawCharacters(int, int)
	at com.google.googlejavaformat.java.JavacTokens$CommentSavingTokenizer.getRawCharactersReflectively(JavacTokens.java:150)
	at com.google.googlejavaformat.java.JavacTokens$CommentSavingTokenizer.processComment(JavacTokens.java:131)
	at com.sun.tools.javac.parser.JavaTokenizer.readToken(JavaTokenizer.java:585)
	at com.sun.tools.javac.parser.Scanner.nextToken(Scanner.java:115)
	at com.google.googlejavaformat.java.JavacTokens.getTokens(JavacTokens.java:88)
	at com.google.googlejavaformat.java.JavaInput.buildToks(JavaInput.java:364)
	at com.google.googlejavaformat.java.JavaInput.buildToks(JavaInput.java:334)
	at com.google.googlejavaformat.java.JavaInput.<init>(JavaInput.java:276)
	at com.google.googlejavaformat.java.Formatter.getFormatReplacements(Formatter.java:280)
	at com.google.googlejavaformat.java.Formatter.formatSource(Formatter.java:267)
	at com.google.googlejavaformat.java.FormatFileCallable.call(FormatFileCallable.java:45)
	at com.google.googlejavaformat.java.FormatFileCallable.call(FormatFileCallable.java:26)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(Thread.java:834)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:527)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
Caused by: java.lang.NoSuchMethodException: com.sun.tools.javac.parser.UnicodeReader.getRawCharacters(int, int)
	at java.lang.Class.getMethod(DynamicHub.java:1053)
	at com.google.googlejavaformat.java.JavacTokens$CommentSavingTokenizer.getRawCharactersReflectively(JavacTokens.java:147)
	... 17 more
```

[ConfigCommand.java.gz](https://github.com/google/google-java-format/files/5968117/ConfigCommand.java.gz)

**Comment by cushon** [comment]
```
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:527)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
```

This is the result of a bad graal vm configuration, I'll follow up internally
