### ISSUE TITLE
NullPointerException when removing unused imports

### ISSUE THREAD

**Issue by gabrielittner** [google/google-java-format#58]
The stacktrace:
```
java.lang.NullPointerException
        at com.google.googlejavaformat.java.RemoveUnusedImports$UnusedImportScanner.recordSimpleName(RemoveUnusedImports.java:123)
        at com.google.googlejavaformat.java.RemoveUnusedImports$UnusedImportScanner.recordReference(RemoveUnusedImports.java:118)
        at com.google.googlejavaformat.java.RemoveUnusedImports$UnusedImportScanner.recordTag(RemoveUnusedImports.java:105)
        at com.google.googlejavaformat.java.RemoveUnusedImports$UnusedImportScanner.access$000(RemoveUnusedImports.java:77)
        at com.google.googlejavaformat.java.RemoveUnusedImports$UnusedImportScanner$1.visit(RemoveUnusedImports.java:88)
        at org.eclipse.jdt.core.dom.TagElement.accept0(TagElement.java:278)
        at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2711)
        at org.eclipse.jdt.core.dom.ASTNode.acceptChildren(ASTNode.java:2782)
        at org.eclipse.jdt.core.dom.TagElement.accept0(TagElement.java:280)
        at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2711)
        at org.eclipse.jdt.core.dom.ASTNode.acceptChildren(ASTNode.java:2782)
        at org.eclipse.jdt.core.dom.Javadoc.accept0(Javadoc.java:205)
        at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2711)
        at com.google.googlejavaformat.java.RemoveUnusedImports$UnusedImportScanner.visit(RemoveUnusedImports.java:84)
        at org.eclipse.jdt.core.dom.Javadoc.accept0(Javadoc.java:202)
        at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2711)
        at org.eclipse.jdt.core.dom.ASTNode.acceptChild(ASTNode.java:2759)
        at org.eclipse.jdt.core.dom.MethodDeclaration.accept0(MethodDeclaration.java:614)
        at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2711)
        at org.eclipse.jdt.core.dom.ASTNode.acceptChildren(ASTNode.java:2782)
        at org.eclipse.jdt.core.dom.TypeDeclaration.accept0(TypeDeclaration.java:470)
        at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2711)
        at org.eclipse.jdt.core.dom.ASTNode.acceptChildren(ASTNode.java:2782)
        at org.eclipse.jdt.core.dom.CompilationUnit.accept0(CompilationUnit.java:212)
        at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2711)
        at com.google.googlejavaformat.java.RemoveUnusedImports.removeUnusedImports(RemoveUnusedImports.java:153)
        at com.google.googlejavaformat.java.FormatFileCallable.call(FormatFileCallable.java:44)
        at com.google.googlejavaformat.java.FormatFileCallable.call(FormatFileCallable.java:28)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

The class where it happens: 
```
package com.gabrielittner.db;

import java.io.Closeable;
import java.util.concurrent.TimeUnit;

/**
 * An in-progress database transaction.
 */
public interface Transaction extends Closeable {
    /**
     * End a transaction. See {@link ReactiveDatabase#newTransaction()} for notes about how to
     * use this and when transactions are committed and rolled back.
     */
    void end();

    /**
     * Marks the current transaction as successful. Do not do any more database work between
     * calling this and calling {@link #end()}. Do as little non-database work as possible in that
     * situation too. If any errors are encountered between this and {@link #end()} the transaction
     * will still be committed.
     */
    void markSuccessful();

    /**
     * Temporarily end the transaction to let other threads run. The transaction is assumed to be
     * successful so far. Do not call {@link #markSuccessful()} before calling this. When this
     * returns a new transaction will have been created but not marked as successful. This assumes
     * that there are no nested transactions (newTransaction has only been called once) and will
     * throw an exception if that is not the case.
     *
     * @return true if the transaction was yielded
     */
    boolean yieldIfContendedSafely();

    /**
     * Temporarily end the transaction to let other threads run. The transaction is assumed to be
     * successful so far. Do not call {@link #markSuccessful()} before calling this. When this
     * returns a new transaction will have been created but not marked as successful. This assumes
     * that there are no nested transactions (newTransaction has only been called once) and will
     * throw an exception if that is not the case.
     *
     * @param sleepAmount if > 0, sleep this long before starting a new transaction if
     *                    the lock was actually yielded. This will allow other background threads
     *                    to make some more progress than they would if we started the transaction
     *                    immediately.
     * @return true if the transaction was yielded
     */
    boolean yieldIfContendedSafely(long sleepAmount, TimeUnit sleepUnit);

    /**
     * Equivalent to calling {@link #end()}
     */
    @Override
    void close();
}
```

I've used a jar built from the latest commit 70ab4ac.

**Comment by cushon** [comment]
70ab4ace7056d50fcfca8a59b63cb5dfb8da095f was half-baked, thanks for the report.
