### ISSUE TITLE
NoSuchMethodError when running 1.10.0

### ISSUE THREAD

**Issue by miraleung** [google/google-java-format#611]
Repro steps:
1. Clone [gapic-generator-java](github.com/googleapis/gapic-generator-java]
2. Update google_java_format to 1.10.0 in dependencies.properties
3. Run `bazel run test/integration:asset_update`, which invokes this formatter via the generator.
4. The formatter crashes with the following log:

```
Exception in thread "main" java.lang.NoSuchMethodError: 'java.lang.Comparable com.google.common.collect.Comparators.max(java.lang.Comparable, java.lang.Comparable)'
	at com.google.googlejavaformat.java.javadoc.JavadocWriter.requestWhitespace(JavadocWriter.java:273)
	at com.google.googlejavaformat.java.javadoc.JavadocWriter.requestWhitespace(JavadocWriter.java:72)
	at com.google.googlejavaformat.java.javadoc.JavadocFormatter.render(JavadocFormatter.java:122)
	at com.google.googlejavaformat.java.javadoc.JavadocFormatter.formatJavadoc(JavadocFormatter.java:52)
	at com.google.googlejavaformat.java.JavaCommentsHelper.rewrite(JavaCommentsHelper.java:47)
	at com.google.googlejavaformat.Doc$Tok.computeBreaks(Doc.java:756)
	at com.google.googlejavaformat.Doc$Level.computeSplit(Doc.java:331)
	at com.google.googlejavaformat.Doc$Level.computeBreakAndSplit(Doc.java:321)
	at com.google.googlejavaformat.Doc$Level.computeBroken(Doc.java:297)
	at com.google.googlejavaformat.Doc$Level.computeBreaks(Doc.java:267)
	at com.google.googlejavaformat.java.Formatter.format(Formatter.java:174)
	at com.google.googlejavaformat.java.Formatter.getFormatReplacements(Formatter.java:291)
	at com.google.googlejavaformat.java.Formatter.formatSource(Formatter.java:267)
	at com.google.googlejavaformat.java.Formatter.formatSource(Formatter.java:233)
	at com.google.api.generator.engine.writer.JavaFormatter.format(JavaFormatter.java:29)
	at com.google.api.generator.engine.writer.JavaWriterVisitor.visit(JavaWriterVisitor.java:965)
	at com.google.api.generator.engine.ast.ClassDefinition.accept(ClassDefinition.java:67)
	at com.google.api.generator.gapic.protowriter.Writer.write(Writer.java:55)
	at com.google.api.generator.gapic.Generator.generateGapic(Generator.java:33)
	at com.google.api.generator.Main.main(Main.java:35)
--java_gapic_out: protoc-gen-java_gapic: Plugin failed with status code 1.
```

**Comment by miraleung** [comment]
Closing - turns out it's due to upgrading a Guava to v30.
