### ISSUE TITLE
NoSuchMethodError when running 1.11.0

### ISSUE THREAD

**Issue by ratcashdev** [google/google-java-format#672]
formatting a class containing classic javadoc
```java
/**
 * 
 *  This is my javadoc
 */
public class MyShinyClass {
  public void myMethod() {
    for (int i = 0; i < 10; i++) {}
  }
}
```
 results in an exception

```
java.lang.NoSuchMethodError: 'java.lang.Comparable com.google.common.collect.Comparators.max(java.lang.Comparable, java.lang.Comparable)'
	at com.google.googlejavaformat.java.javadoc.JavadocWriter.requestWhitespace(JavadocWriter.java:273)
	at com.google.googlejavaformat.java.javadoc.JavadocWriter.requestWhitespace(JavadocWriter.java:72)
	at com.google.googlejavaformat.java.javadoc.JavadocFormatter.render(JavadocFormatter.java:122)
	at com.google.googlejavaformat.java.javadoc.JavadocFormatter.formatJavadoc(JavadocFormatter.java:52)
	at com.google.googlejavaformat.java.JavaCommentsHelper.rewrite(JavaCommentsHelper.java:47)
	at com.google.googlejavaformat.Doc$Tok.computeBreaks(Doc.java:756)
	at com.google.googlejavaformat.Doc$Level.computeSplit(Doc.java:331)
	at com.google.googlejavaformat.Doc$Level.computeBreakAndSplit(Doc.java:321)
	at com.google.googlejavaformat.Doc$Level.computeBroken(Doc.java:297)
	at com.google.googlejavaformat.Doc$Level.computeBreaks(Doc.java:267)
	at com.google.googlejavaformat.java.Formatter.format(Formatter.java:174)
	at com.google.googlejavaformat.java.Formatter.getFormatReplacements(Formatter.java:291)
	at com.google.googlejavaformat.java.Formatter.formatSource(Formatter.java:267)
```

this is caused by guava v30, it seems.

**Comment by ratcashdev** [comment]
Just realized this as well, thanks.
