### ISSUE TITLE
Exception in 2022.3 UE

### ISSUE THREAD

**Issue by balane** [google/google-java-format#866]
```
java.lang.RuntimeException: Cannot find service software.aws.toolkits.jetbrains.services.codewhisperer.explorer.CodeWhispererExplorerActionManager (classloader=PluginClassLoader(plugin=PluginDescriptor(name=AWS Toolkit, id=aws.toolkit, descriptorPath=plugin.xml, path=C:\apps\toolbox\apps\IDEA-U\ch-0\223.7571.182.plugins\aws-toolkit-jetbrains, version=1.55-223, package=null, isBundled=false), packagePrefix=null, instanceId=362, state=unload in progress), client=null)
	at software.aws.toolkits.jetbrains.services.codewhisperer.explorer.CodeWhispererExplorerActionManager$Companion.getInstance(CodeWhispererExplorerActionManager.kt:290)
	at software.aws.toolkits.jetbrains.services.codewhisperer.editor.CodeWhispererEditorListener$editorCreated$1$1$1.documentChanged(CodeWhispererEditorListener.kt:28)
	at com.intellij.openapi.editor.impl.DocumentImpl.lambda$changedUpdate$2(DocumentImpl.java:922)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeNonCancelableSection$3(CoreProgressManager.java:226)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:666)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:622)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$computeInNonCancelableSection$4(CoreProgressManager.java:234)
	at com.intellij.openapi.progress.Cancellation.computeInNonCancelableSection(Cancellation.java:99)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeInNonCancelableSection(CoreProgressManager.java:234)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeNonCancelableSection(CoreProgressManager.java:225)
	at com.intellij.openapi.editor.impl.DocumentImpl.changedUpdate(DocumentImpl.java:919)
	at com.intellij.openapi.editor.impl.DocumentImpl.updateText(DocumentImpl.java:823)
	at com.intellij.openapi.editor.impl.DocumentImpl.replaceString(DocumentImpl.java:664)
	at com.intellij.openapi.editor.impl.DocumentImpl.replaceString(DocumentImpl.java:601)
	at com.intellij.psi.formatter.DocumentBasedFormattingModel.replaceWhiteSpace(DocumentBasedFormattingModel.java:151)
	at com.intellij.formatting.engine.FormatProcessorUtils.replaceWhiteSpace(FormatProcessorUtils.java:31)
	at com.intellij.formatting.engine.ApplyChangesState.doIteration(ApplyChangesState.java:175)
	at com.intellij.formatting.engine.State.iteration(State.java:25)
	at com.intellij.formatting.engine.StateProcessor.iteration(StateProcessor.java:26)
	at com.intellij.formatting.FormatProcessor.doIterationsSynchronously(FormatProcessor.java:148)
	at com.intellij.formatting.FormatProcessor.performModifications(FormatProcessor.java:143)
	at com.intellij.formatting.FormatProcessor.performModifications(FormatProcessor.java:133)
	at com.intellij.formatting.FormatterImpl.adjustLineIndentsForRange(FormatterImpl.java:298)
	at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerImpl$3.doPerform(CodeStyleManagerImpl.java:296)
	at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerRunnable.perform(CodeStyleManagerRunnable.java:93)
	at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerImpl.adjustLineIndent(CodeStyleManagerImpl.java:299)
	at com.google.googlejavaformat.intellij.CodeStyleManagerDecorator.adjustLineIndent(CodeStyleManagerDecorator.java:116)
	at jdk.internal.reflect.GeneratedMethodAccessor1350.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at krasa.formatter.plugin.ProxyCodeStyleManagerDelegator.PLEASE_REPORT_BUGS_TO_JETBRAINS_IF_IT_FAILS_HERE____ORIGINAL_INTELLIJ_FORMATTER_WAS_USED(ProxyCodeStyleManagerDelegator.java:60)
	at krasa.formatter.plugin.ProxyCodeStyleManagerDelegator.invoke(ProxyCodeStyleManagerDelegator.java:28)
	at com.intellij.psi.codeStyle.CodeStyleManager$$EnhancerByCGLIB$$a6c18dd5.adjustLineIndent(<generated>)
	at com.intellij.codeInsight.editorActions.DefaultTypingActionsExtension.adjustLineIndent(DefaultTypingActionsExtension.java:86)
	at com.intellij.codeInsight.editorActions.DefaultTypingActionsExtension.indentEachLine(DefaultTypingActionsExtension.java:165)
	at com.intellij.codeInsight.editorActions.DefaultTypingActionsExtension.format(DefaultTypingActionsExtension.java:66)
	at com.intellij.codeInsight.editorActions.PasteHandler.lambda$doPasteAction$5(PasteHandler.java:266)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:955)
	at com.intellij.codeInsight.editorActions.PasteHandler.doPasteAction(PasteHandler.java:264)
	at com.intellij.codeInsight.editorActions.PasteHandler.doPaste(PasteHandler.java:119)
	at com.intellij.codeInsight.editorActions.PasteHandler.lambda$execute$2(PasteHandler.java:100)
	at com.intellij.openapi.project.DumbService.runWithAlternativeResolveEnabled(DumbService.java:386)
	at com.intellij.codeInsight.editorActions.PasteHandler.execute(PasteHandler.java:91)
	at com.intellij.bigdatatools.zeppelin.editor.actions.ZeppelinPasteHandler.execute(ZeppelinPasteHandler.kt:29)
	at com.intellij.codeInsight.editorActions.PasteHandler.doExecute(PasteHandler.java:57)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.lambda$execute$4(EditorActionHandler.java:199)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.doIfEnabled(EditorActionHandler.java:89)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.execute(EditorActionHandler.java:198)
	at com.intellij.codeInsight.editorActions.LanguageConsolePasteHandler.doExecute(LanguageConsolePasteHandler.kt:24)
	at com.intellij.openapi.editor.actionSystem.DynamicEditorActionHandler.doExecute(DynamicEditorActionHandler.java:63)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.lambda$execute$4(EditorActionHandler.java:199)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.doIfEnabled(EditorActionHandler.java:89)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.execute(EditorActionHandler.java:198)
	at com.intellij.openapi.editor.actionSystem.EditorAction.lambda$actionPerformed$0(EditorAction.java:93)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:219)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:174)
	at com.intellij.openapi.editor.actionSystem.EditorAction.actionPerformed(EditorAction.java:102)
	at com.intellij.openapi.editor.actionSystem.EditorAction.actionPerformed(EditorAction.java:77)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.doPerformActionOrShowPopup(ActionUtil.java:323)
	at com.intellij.openapi.keymap.impl.ActionProcessor.performAction(ActionProcessor.java:47)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:584)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$doPerformActionInner$9(IdeKeyEventDispatcher.java:706)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:94)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$doPerformActionInner$10(IdeKeyEventDispatcher.java:706)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:346)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.doPerformActionInner(IdeKeyEventDispatcher.java:703)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:647)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:595)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processActionOrWaitSecondStroke(IdeKeyEventDispatcher.java:478)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:467)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:225)
	at com.intellij.ide.IdeEventQueue.dispatchKeyEvent(IdeEventQueue.java:815)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:750)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$5(IdeEventQueue.java:437)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:774)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:436)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:113)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:615)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:434)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:813)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:480)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

IntelliJ IDEA 2022.3 (Ultimate Edition)
Build #IU-223.7571.182, built on November 29, 2022
Licensed to xxxxx
Subscription is active until August 5, 2023.
Runtime version: 17.0.5+1-b653.14 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 5000M
Cores: 8
Registry:
    ide.balloon.shadow.size=0
    editor.minimap.enabled=true
    js.debugger.webconsole=false

Non-Bundled Plugins:
    org.jetbrains.plugins.go (223.7571.182)
    Batch Scripts Support (1.0.13)
    org.intellij.RegexpTester (1.0.8)
    com.fxiaoke.lizc8407 (2.0.0)
    com.denis.zaichenko.angular.2.ws.live.templates (2.0.0)
    com.xrath.plugin.fold (1.5.0)
    com.checkmarx.intellij (9.00.29)
    EclipseCodeFormatter (22.0.203.000.0-Eclipse_2021-09)
    com.oliverlockwood.plugins.jenkinsfile (1.0)
    com.intellij.plugin.adernov.powershell (2.0.10)
    google-java-format (1.15.0.0)
    org.jetbrains.plugins.spotbugs (1.2.5)
    com.williamlee.plugin.swagger.generate (1.0)
    org.jetbrains.plugins.go-template (223.7571.203)
    com.hasintech.intellij.angularTemplates (1.1.3)
    tv.twelvetone.intellij.plugins.intellivue (1.1.20)
    Pythonid (223.7571.182)
    MavenRunHelper (4.23.222.2964.0)
    patrick.kelleter.angular-cli-quick-switch (1.3)
    ru.adelf.idea.dotenv (2022.3)
    org.intellij.scala (2022.3.13)
    com.intellij.bigdatatools (223.7571.214)
    com.github.ragurney.spotless (1.0.9)

Kotlin: 223-1.7.20-release-201-IJ7571.182

**Comment by balane** [comment]
I'm not seeing this anymore. Closing.
