### ISSUE TITLE
Intellij Plugin 1.16.0.0 is broken in 2022.3.2

### ISSUE THREAD

**Issue by dschulten** [google/google-java-format#908]
1.16.0.0 is broken in 2022.3.2 Build #IU-223.8617.56, in spite of adding the new code export as described: 
--add-opens=java.base/java.lang=ALL-UNNAMED 
--add-opens=java.base/java.util=ALL-UNNAMED 
--add-exports jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED 
--add-exports jdk.compiler/com.sun.tools.javac.code=ALL-UNNAMED 
--add-exports jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED 
--add-exports jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED 
--add-exports jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED 
--add-exports jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED

Symptom: Formatting the code shows a bubble saying that the code is already formatted and nothing happens.

Log extract shows nothing that would be helpful for users:
```
2023-03-06 08:32:07,081 [ 352617]   WARN - #c.i.o.o.n.SettingsTreeView$MyBuilder - 'AbstractTreeBuilder' is going to be dropped soon and must not be used
com.intellij.diagnostic.PluginException: 'AbstractTreeBuilder' is going to be dropped soon and must not be used
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:83)
	at com.intellij.ide.util.treeView.AbstractTreeBuilder.<init>(AbstractTreeBuilder.java:60)
	at com.intellij.ide.util.treeView.AbstractTreeBuilder.<init>(AbstractTreeBuilder.java:55)
	at com.intellij.ide.util.treeView.AbstractTreeBuilder.<init>(AbstractTreeBuilder.java:47)
	at com.intellij.ui.treeStructure.filtered.FilteringTreeBuilder.<init>(FilteringTreeBuilder.java:46)
	at com.intellij.openapi.options.newEditor.SettingsTreeView$MyBuilder.<init>(SettingsTreeView.java:931)
	at com.intellij.openapi.options.newEditor.SettingsTreeView.<init>(SettingsTreeView.java:174)
	at com.intellij.openapi.options.newEditor.SettingsDialog.treeViewFactory(SettingsDialog.java:89)
	at com.intellij.openapi.options.newEditor.SettingsEditor.<init>(SettingsEditor.java:194)
	at com.intellij.openapi.options.newEditor.SettingsDialog.<init>(SettingsDialog.java:65)
	at com.intellij.openapi.options.newEditor.SettingsDialogFactory.create(SettingsDialogFactory.java:38)
	at com.intellij.ide.actions.ShowSettingsUtilImpl.getDialog(ShowSettingsUtilImpl.java:39)
	at com.intellij.ide.actions.ShowSettingsUtilImpl.showSettingsDialog(ShowSettingsUtilImpl.java:90)
	at com.intellij.ide.actions.ShowSettingsAction.perform(ShowSettingsAction.java:60)
	at com.intellij.ide.actions.ShowSettingsAction.actionPerformed(ShowSettingsAction.java:47)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.doPerformActionOrShowPopup(ActionUtil.java:327)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.lambda$performActionDumbAwareWithCallbacks$4(ActionUtil.java:306)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:350)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAwareWithCallbacks(ActionUtil.java:306)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$performAction$5(ActionMenuItem.java:296)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:226)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.performAction(ActionMenuItem.java:289)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$new$0(ActionMenuItem.java:64)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$fireActionPerformed$4(ActionMenuItem.java:111)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:94)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:111)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.doClick(BegMenuItemUI.java:526)
	at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:558)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6648)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3392)
	at java.desktop/java.awt.Component.processEvent(Component.java:6413)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5022)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4854)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2802)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4854)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:781)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:730)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:754)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:752)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:751)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:909)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:831)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:753)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$5(IdeEventQueue.java:437)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:436)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:113)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:615)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:434)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:838)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:480)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
2023-03-06 08:33:37,679 [ 443215]   INFO - #c.i.i.b.BookmarkManager - no state loaded for old bookmarks
2023-03-06 08:33:37,700 [ 443236]   INFO - #c.i.i.f.FavoritesManager - no state loaded for old favorites
2023-03-06 08:34:25,457 [ 490993]   WARN - #c.i.o.o.e.ConfigurableCardPanel - auto-dispose 'Plugins' id=preferences.pluginManager
2023-03-06 08:34:42,906 [ 508442]   INFO - #c.i.c.ComponentStoreImpl - Saving appActionsLocalSummary took 16 ms, AsciidocApplicationSettings took 196 ms, CodeInsightSettings took 48 ms, FileTypeManager took 66 ms, NotRoamableUiSettings took 57 ms, PluginAdvertiserExtensions took 25 ms, TemplateSettings took 296 ms, TextMateSettings took 203 ms
2023-03-06 08:34:45,829 [ 511365]   WARN - #c.i.u.x.Binding - no accessors for org.jetbrains.idea.perforce.perforce.ConnectionId
2023-03-06 08:34:45,920 [ 511456]   INFO - #c.i.c.ComponentStoreImpl - Saving Project(name=xmeldnachrichten, containerState=COMPONENT_CREATED, componentStore=C:\Users\Schulten\Documents\projekte\meldeportal\services\xmeldnachrichten)RunManager took 21 ms, TaskManager took 11 ms, XDebuggerManager took 15 ms
2023-03-06 08:34:46,116 [ 511652]   INFO - #c.i.o.c.i.s.StoreUtil - saveProjectsAndApp took 4341 ms
2023-03-06 08:35:03,763 [ 529299]   WARN - #c.i.o.o.e.ConfigurableExtensionPointUtil - ignore deprecated groupId: language for id: camel.annotator
2023-03-06 08:35:03,765 [ 529301]   WARN - #c.i.o.o.e.ConfigurableExtensionPointUtil - ignore deprecated groupId: language for id: camel.misc
2023-03-06 08:35:03,766 [ 529302]   WARN - #c.i.o.o.e.ConfigurableExtensionPointUtil - ignore deprecated groupId: language for id: camel.properties
2023-03-06 08:35:03,789 [ 529325]   WARN - #c.i.o.o.e.ConfigurableExtensionPointUtil - ignore deprecated groupId: language for id: preferences.language.Kotlin.scripting
2023-03-06 08:36:54,761 [ 640297]   WARN - #c.i.o.o.e.ConfigurableCardPanel - auto-dispose 'Plugins' id=preferences.pluginManager
2023-03-06 08:36:55,271 [ 640807]   INFO - #c.i.c.ComponentStoreImpl - Saving appEditorSettings took 55 ms, FileTypeManager took 21 ms
2023-03-06 08:36:55,378 [ 640914]   INFO - #c.i.c.ComponentStoreImpl - Saving Project(name=xmeldnachrichten, containerState=COMPONENT_CREATED, componentStore=C:\Users\Schulten\Documents\projekte\meldeportal\services\xmeldnachrichten)RunManager took 14 ms
2023-03-06 08:36:58,258 [ 643794]   INFO - #c.i.c.ComponentStoreImpl - Saving appFileTypeManager took 22 ms
2023-03-06 08:36:58,319 [ 643855]   INFO - #c.i.c.ComponentStoreImpl - Saving Project(name=xmeldnachrichten, containerState=COMPONENT_CREATED, componentStore=C:\Users\Schulten\Documents\projekte\meldeportal\services\xmeldnachrichten)RunManager took 12 ms
2023-03-06 08:37:43,993 [ 689529]   INFO - #c.i.c.ComponentStoreImpl - Saving appFileTypeManager took 12 ms
2023-03-06 08:37:44,125 [ 689661]   INFO - #c.i.c.ComponentStoreImpl - Saving Project(name=xmeldnachrichten, containerState=COMPONENT_CREATED, componentStore=C:\Users\Schulten\Documents\projekte\meldeportal\services\xmeldnachrichten)MavenProjectsManager took 13 ms, RemoteRepositoriesConfiguration took 17 ms, RunManager took 17 ms
2023-03-06 08:38:36,044 [ 741580]   WARN - #c.i.o.o.e.ConfigurableExtensionPointUtil - ignore deprecated groupId: language for id: camel.annotator
2023-03-06 08:38:36,045 [ 741581]   WARN - #c.i.o.o.e.ConfigurableExtensionPointUtil - ignore deprecated groupId: language for id: camel.misc
2023-03-06 08:38:36,045 [ 741581]   WARN - #c.i.o.o.e.ConfigurableExtensionPointUtil - ignore deprecated groupId: language for id: camel.properties
2023-03-06 08:38:36,067 [ 741603]   WARN - #c.i.o.o.e.ConfigurableExtensionPointUtil - ignore deprecated groupId: language for id: preferences.language.Kotlin.scripting
2023-03-06 08:42:55,022 [1000558]   INFO - #git4idea.commands.GitHandler - [..\importservice] git -c credential.helper= -c core.quotepath=false -c log.showSignature=false fetch origin --recurse-submodules=no --progress --prune
2023-03-06 08:42:55,023 [1000559]   INFO - #git4idea.commands.GitHandler - [..\commons-meldeportal] git -c credential.helper= -c core.quotepath=false -c log.showSignature=false fetch origin --recurse-submodules=no --progress --prune
2023-03-06 08:42:55,026 [1000562]   INFO - #git4idea.commands.GitHandler - [xmeldnachrichten] git -c credential.helper= -c core.quotepath=false -c log.showSignature=false fetch origin --recurse-submodules=no --progress --prune
2023-03-06 08:42:55,031 [1000567]   INFO - #git4idea.commands.GitHandler - [..\personendatenimport] git -c credential.helper= -c core.quotepath=false -c log.showSignature=false fetch origin --recurse-submodules=no --progress --prune
2023-03-06 08:42:55,033 [1000569]   INFO - #git4idea.commands.GitHandler - [..\commons-personensuche] git -c credential.helper= -c core.quotepath=false -c log.showSignature=false fetch origin --recurse-submodules=no --progress --prune
2023-03-06 08:42:55,047 [1000583]   INFO - #git4idea.commands.GitHandler - [..\web-bff] git -c credential.helper= -c core.quotepath=false -c log.showSignature=false fetch origin --recurse-submodules=no --progress --prune
2023-03-06 08:42:55,054 [1000590]   INFO - #git4idea.commands.GitHandler - [..\personensuche] git -c credential.helper= -c core.quotepath=false -c log.showSignature=false fetch origin --recurse-submodules=no --progress --prune
2023-03-06 08:46:02,478 [1188014]   WARN - #c.i.o.o.e.ConfigurableCardPanel - auto-dispose 'Plugins' id=preferences.pluginManager
2023-03-06 08:46:03,057 [1188593]   INFO - #c.i.c.ComponentStoreImpl - Saving appAsciidocApplicationSettings took 37 ms, GitToolBoxAppSettings2 took 12 ms, PlantUmlSettingsNew took 28 ms
2023-03-06 08:46:03,218 [1188754]   INFO - #c.i.c.ComponentStoreImpl - Saving Project(name=xmeldnachrichten, containerState=COMPONENT_CREATED, componentStore=C:\Users\Schulten\Documents\projekte\meldeportal\services\xmeldnachrichten)RunManager took 11 ms
2023-03-06 08:46:07,064 [1192600]   WARN - #c.i.o.o.e.ConfigurableExtensionPointUtil - ignore deprecated groupId: language for id: camel.annotator
2023-03-06 08:46:07,065 [1192601]   WARN - #c.i.o.o.e.ConfigurableExtensionPointUtil - ignore deprecated groupId: language for id: camel.misc
2023-03-06 08:46:07,065 [1192601]   WARN - #c.i.o.o.e.ConfigurableExtensionPointUtil - ignore deprecated groupId: language for id: camel.properties
2023-03-06 08:46:07,091 [1192627]   WARN - #c.i.o.o.e.ConfigurableExtensionPointUtil - ignore deprecated groupId: language for id: preferences.language.Kotlin.scripting
2023-03-06 08:46:49,366 [1234902]   WARN - #c.i.o.o.e.ConfigurableCardPanel - auto-dispose 'Plugins' id=preferences.pluginManager
2023-03-06 08:46:49,859 [1235395]   INFO - #c.i.c.ComponentStoreImpl - Saving appVcs.Log.App.Settings took 38 ms
2023-03-06 08:46:49,987 [1235523]   INFO - #c.i.c.ComponentStoreImpl - Saving Project(name=xmeldnachrichten, containerState=COMPONENT_CREATED, componentStore=C:\Users\Schulten\Documents\projekte\meldeportal\services\xmeldnachrichten)KotlinCommonCompilerArguments took 15 ms, RunManager took 19 ms
2023-03-06 08:46:58,203 [1243739]   INFO - #c.i.u.MemTester - not supported: Windows is not supported
2023-03-06 08:47:10,193 [1255729]   INFO - #c.i.c.ComponentStoreImpl - Saving appAsciidocApplicationSettings took 16 ms, FileTypeManager took 15 ms, GeneralSettings took 114 ms, TemplateSettings took 11 ms, XDebuggerSettings took 11 ms
2023-03-06 08:47:10,568 [1256104]   INFO - #c.i.c.ComponentStoreImpl - Saving Project(name=xmeldnachrichten, containerState=COMPONENT_CREATED, componentStore=C:\Users\Schulten\Documents\projekte\meldeportal\services\xmeldnachrichten)EclipseCodeFormatterProjectSettings took 25 ms, Kotlin2JvmCompilerArguments took 150 ms, RunManager took 134 ms
2023-03-06 08:48:24,277 [1329813]   INFO - #c.i.o.a.i.PopupMenuPreloader - 4112 ms since showing to preload popup menu 'Editor Popup Menu' at 'EditorPopup(preload-bgt)' in 433 ms
2023-03-06 08:48:24,464 [1330000]   INFO - #c.i.o.a.i.PopupMenuPreloader - 4326 ms since showing to preload popup menu 'Editor Popup Menu' at 'EditorPopup(preload-bgt)' in 621 ms
```

**Comment by Djaytan** [comment]
Thanks @amammad, it's for sure better now with your input!

But now I have the following error on my side: https://github.com/google/google-java-format/issues/911

This is less critical, but this remains annoying
