### ISSUE TITLE
JDK 9, Snapshot 1.2 and remove unused imports fails

### ISSUE THREAD

**Issue by sormuras** [google/google-java-format#91]
Somehow related to #86 - but here an internal API field is hiding although the modules are explicitly added via JVM parameters. See the stacktrace produced running GJF on JDK 9, Windows and using Gradle as a launch tool:
```
java.lang.NoSuchFieldError: paramTypes
	at com.google.googlejavaformat.java.RemoveUnusedImports$UnusedImportScanner$DocTreeScanner.visitReference(RemoveUnusedImports.java:165)
	at com.google.googlejavaformat.java.RemoveUnusedImports$UnusedImportScanner$DocTreeScanner.visitReference(RemoveUnusedImports.java:147)
	at com.sun.tools.javac.tree.DCTree$DCReference.accept(jdk.compiler@9-ea/DCTree.java:601)
	at com.sun.source.util.DocTreePathScanner.scan(jdk.compiler@9-ea/DocTreePathScanner.java:71)
	at com.sun.source.util.DocTreeScanner.scan(jdk.compiler@9-ea/DocTreeScanner.java:99)
	at com.sun.source.util.DocTreeScanner.visitSee(jdk.compiler@9-ea/DocTreeScanner.java:361)
	at com.sun.tools.javac.tree.DCTree$DCSee.accept(jdk.compiler@9-ea/DCTree.java:647)
	at com.sun.source.util.DocTreePathScanner.scan(jdk.compiler@9-ea/DocTreePathScanner.java:71)
	at com.sun.source.util.DocTreeScanner.scan(jdk.compiler@9-ea/DocTreeScanner.java:99)
	at com.sun.source.util.DocTreeScanner.scanAndReduce(jdk.compiler@9-ea/DocTreeScanner.java:107)
	at com.sun.source.util.DocTreeScanner.visitDocComment(jdk.compiler@9-ea/DocTreeScanner.java:186)
	at com.sun.tools.javac.tree.DCTree$DCDocComment.accept(jdk.compiler@9-ea/DCTree.java:132)
	at com.sun.source.util.DocTreePathScanner.scan(jdk.compiler@9-ea/DocTreePathScanner.java:50)
	at com.google.googlejavaformat.java.RemoveUnusedImports$UnusedImportScanner.scanJavadoc(RemoveUnusedImports.java:143)
	at com.google.googlejavaformat.java.RemoveUnusedImports$UnusedImportScanner.scan(RemoveUnusedImports.java:131)
	at com.google.googlejavaformat.java.RemoveUnusedImports$UnusedImportScanner.scan(RemoveUnusedImports.java:99)
	at com.sun.source.util.TreeScanner.visitClass(jdk.compiler@9-ea/TreeScanner.java:183)
	at com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(jdk.compiler@9-ea/JCTree.java:794)
	at com.sun.source.util.TreePathScanner.scan(jdk.compiler@9-ea/TreePathScanner.java:71)
	at com.google.googlejavaformat.java.RemoveUnusedImports$UnusedImportScanner.scan(RemoveUnusedImports.java:132)
	at com.google.googlejavaformat.java.RemoveUnusedImports$UnusedImportScanner.scan(RemoveUnusedImports.java:99)
	at com.sun.source.util.TreeScanner.scan(jdk.compiler@9-ea/TreeScanner.java:105)
	at com.sun.source.util.TreeScanner.scanAndReduce(jdk.compiler@9-ea/TreeScanner.java:113)
	at com.sun.source.util.TreeScanner.visitClass(jdk.compiler@9-ea/TreeScanner.java:187)
	at com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(jdk.compiler@9-ea/JCTree.java:794)
	at com.sun.source.util.TreePathScanner.scan(jdk.compiler@9-ea/TreePathScanner.java:71)
	at com.google.googlejavaformat.java.RemoveUnusedImports$UnusedImportScanner.scan(RemoveUnusedImports.java:132)
	at com.google.googlejavaformat.java.RemoveUnusedImports$UnusedImportScanner.scan(RemoveUnusedImports.java:99)
	at com.sun.source.util.TreeScanner.scan(jdk.compiler@9-ea/TreeScanner.java:105)
	at com.sun.source.util.TreeScanner.scanAndReduce(jdk.compiler@9-ea/TreeScanner.java:113)
	at com.sun.source.util.TreeScanner.visitCompilationUnit(jdk.compiler@9-ea/TreeScanner.java:144)
	at com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(jdk.compiler@9-ea/JCTree.java:577)
	at com.sun.source.util.TreePathScanner.scan(jdk.compiler@9-ea/TreePathScanner.java:71)
	at com.google.googlejavaformat.java.RemoveUnusedImports$UnusedImportScanner.scan(RemoveUnusedImports.java:132)
	at com.google.googlejavaformat.java.RemoveUnusedImports.removeUnusedImports(RemoveUnusedImports.java:204)
	at com.google.googlejavaformat.java.FormatFileCallable.fixImports(FormatFileCallable.java:53)
	at com.google.googlejavaformat.java.FormatFileCallable.call(FormatFileCallable.java:47)
	at com.google.googlejavaformat.java.FormatFileCallable.call(FormatFileCallable.java:27)
	at java.util.concurrent.FutureTask.run(java.base@9-ea/FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@9-ea/ThreadPoolExecutor.java:1158)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@9-ea/ThreadPoolExecutor.java:632)
	at java.lang.Thread.run(java.base@9-ea/Thread.java:843)
```

**Comment by sormuras** [comment]
Workaround. If I remove following referencing tags from Javadoc blocks:

- `{@link java.lang.Object}`
- `@see java.time.Instant#ofEpochMilli(long)`

everythings fine - the visitor does not visit the references at all.

**Comment by sormuras** [comment]
I think, I found the underlying reason: https://stackoverflow.com/questions/5586633/nosuchfielderror-but-the-field-is-there

GJF must be recompiled with Java 9 to update its reference to that `static final` field...

**Comment by cushon** [comment]
This is the same issue as #86.
